
[package]
name = "uil"
version = "0.0.1"
authors = ["Nemikolh <joan.varvenne@gmail.com>"]
homepage = "http://uil-lang.github.io/"
repository = "https://github.com/uil-lang/uil-rs"
readme = "README.md"
license = "MIT"
keywords = ["ui", "opengl", "gamedev"]
description = "User interface library oriented for games. It includes a user interface language: uil."

[features]
use_glium = ["glium", "glium_macros", "glutin", "image"]

[dependencies.xml-rs]
# version = "*"
git = "https://github.com/Nemikolh/xml-rs"

[dependencies]
bitflags = "0.1"
phf = "*"
phf_macros = "*"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
optional = true

[dependencies.glium_macros]
git = "https://github.com/tomaka/glium"
optional = true

[dependencies.glutin]
version = "*"
optional = true

[dependencies.image]
version = "*"
optional = true

[dev-dependencies.cgmath]
version = "*"

[dev-dependencies]
clock_ticks = "*"
