
[package]
name = "uil"
version = "0.0.1"
authors = ["Nemikolh <joan.varvenne@gmail.com>"]

[dependencies.xml-rs]
# version = "*"
git = "https://github.com/Nemikolh/xml-rs"

[dependencies]
bitflags = "0.1"
phf = "0.6.12"
phf_macros = "0.6.12"

[dev-dependencies.glium]
git = "https://github.com/tomaka/glium"
[dev-dependencies.glium_macros]
git = "https://github.com/tomaka/glium"
[dev-dependencies.glutin]
git = "https://github.com/tomaka/glutin"
[dev-dependencies.image]
git = "https://github.com/PistonDevelopers/image"
[dev-dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
[dev-dependencies]
clock_ticks = "*"
