
[package]
name = "uil"
version = "0.0.1"
authors = ["Nemikolh <joan.varvenne@gmail.com>"]
homepage = "http://uil-lang.github.io/"
repository = "https://github.com/uil-lang/uil-rs"
readme = "README.md"
license = "MIT"
keywords = ["ui", "opengl", "gamedev"]
description = "User interface library oriented for games. It includes a user interface language: uil."

[features]
use_glium = ["glium", "glutin"]

[dependencies.xml-rs]
# version = "*"
git = "https://github.com/Nemikolh/xml-rs"

[dependencies]
bitflags = "0.1"
phf = "0.6.12"
phf_macros = "0.6.12"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
optional = true

[dependencies.glium_macros]
git = "https://github.com/tomaka/glium"
optional = true

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
optional = true

[dev-dependencies.image]
git = "https://github.com/PistonDevelopers/image"
[dev-dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"
[dev-dependencies]
clock_ticks = "*"
